spring:
  application:
    name: hmiManagement
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
      active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/hmidb
    username: hmiuser
    password: hmipassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HMIDB

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update      # 운영환경에서는 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

application:
    security:
      jwt:
        secret-key: 462243615E645266556A586E3272355558712F21334448452B6B625065536856
        expiration: 60000
        refresh-token:
          expiration: 604800000